export const users = [
  {
    id: 1,
    email: 'admin@admin.com',
    pswd: '$2a$10$abSN4fkVx4xTxY15dVDhiOI0S47BS5eNKNtwatBXqL2rMYa6671u2',
    usrname: 'James Ney',
    avatar: 'https://randomuser.me/api/portraits/men/30.jpg',
    isActive: true,
    isVolunteer: false,
    petCoins: 10,
    pets: [6],
  },
  {
    id: 2,
    email: 'user@user.com',
    pswd: '$2a$10$kECcRSi92xutgx0.RAZYMe/Tk./1k9dgRyoMsX.PHciGHvSo1Ebq.',
    usrname: 'John Doe',
    avatar: 'https://randomuser.me/api/portraits/men/39.jpg',
    isActive: true,
    isVolunteer: true,
    petCoins: 5,
    pets: [1, 5, 2],
  },
  {
    id: 3,
    email: 'user2@user.com',
    pswd: '$2a$10$kECcRSi92xutgx0.RAZYMe/Tk./1k9dgRyoMsX.PHciGHvSo1Ebq.',
    usrname: 'Mary Jane',
    avatar: 'https://randomuser.me/api/portraits/women/17.jpg',
    isActive: false,
    isVolunteer: false,
    petCoins: 120,
    pets: [],
  },
];
